import type { Person } from './types';

export const mockPeople: Person[] = [
  {
    id: 1,
    nome: "João da Silva Sauro",
    idade: 28,
    dataDesaparecimento: "2025-08-15",
    foto: "https://ui-avatars.com/api/?name=Joao+Sauro&background=E57373&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Masculino",
    cidade: "Cuiabá",
    estado: "MT",
    caracteristicas: "Tatuagem de um dinossauro no antebraço direito, cicatriz na sobrancelha esquerda."
  },
  {
    id: 2,
    nome: "Maria Oliveira",
    idade: 45,
    dataDesaparecimento: "2025-07-20",
    foto: "https://ui-avatars.com/api/?name=Maria+Oliveira&background=81C784&color=FFFFFF&size=400",
    status: 'LOCALIZADO',
    sexo: "Feminino",
    cidade: "Várzea Grande",
    estado: "MT",
    caracteristicas: "Cabelos castanhos compridos, usa óculos de grau com armação vermelha."
  },
  {
    id: 3,
    nome: "Carlos Pereira",
    idade: 19,
    dataDesaparecimento: "2025-09-01",
    foto: "https://ui-avatars.com/api/?name=Carlos+Pereira&background=64B5F6&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Masculino",
    cidade: "Rondonópolis",
    estado: "MT",
    caracteristicas: "Usa aparelho nos dentes, visto pela última vez com uma mochila preta."
  },
  {
    id: 4,
    nome: "Ana Souza",
    idade: 33,
    dataDesaparecimento: "2025-06-10",
    foto: "https://ui-avatars.com/api/?name=Ana+Souza&background=FFB74D&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Feminino",
    cidade: "Sinop",
    estado: "MT",
    caracteristicas: "Pinta no lado direito do rosto, cabelo loiro curto."
  },
  {
    id: 5,
    nome: "Lucas Mendes",
    idade: 22,
    dataDesaparecimento: "2025-08-30",
    foto: "https://ui-avatars.com/api/?name=Lucas+Mendes&background=9575CD&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Masculino",
    cidade: "Cáceres",
    estado: "MT",
    caracteristicas: "Barba por fazer, usa boné de aba reta com frequência."
  },
  {
    id: 6,
    nome: "Juliana Costa",
    idade: 29,
    dataDesaparecimento: "2025-05-18",
    foto: "https://ui-avatars.com/api/?name=Juliana+Costa&background=4DB6AC&color=FFFFFF&size=400",
    status: 'LOCALIZADO',
    sexo: "Feminino",
    cidade: "Tangará da Serra",
    estado: "MT",
    caracteristicas: "Olhos verdes, sardas no rosto."
  },
  {
    id: 7,
    nome: "Pedro Rocha",
    idade: 35,
    dataDesaparecimento: "2025-09-12",
    foto: "https://ui-avatars.com/api/?name=Pedro+Rocha&background=795548&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Masculino",
    cidade: "Sorriso",
    estado: "MT",
    caracteristicas: "Cabelo grisalho nas laterais, dirige um carro prata."
  },
  {
    id: 8,
    nome: "Beatriz Almeida",
    idade: 21,
    dataDesaparecimento: "2025-08-22",
    foto: "https://ui-avatars.com/api/?name=Beatriz+Almeida&background=F06292&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Feminino",
    cidade: "Barra do Garças",
    estado: "MT",
    caracteristicas: "Usa piercing no nariz, vista pela última vez perto da universidade."
  },
  {
    id: 9,
    nome: "Ricardo Lima",
    idade: 52,
    dataDesaparecimento: "2025-04-05",
    foto: "https://ui-avatars.com/api/?name=Ricardo+Lima&background=455A64&color=FFFFFF&size=400",
    status: 'LOCALIZADO',
    sexo: "Masculino",
    cidade: "Primavera do Leste",
    estado: "MT",
    caracteristicas: "Bigode, usa chapéu com frequência."
  },
  {
    id: 10,
    nome: "Fernanda Gonçalves",
    idade: 26,
    dataDesaparecimento: "2025-09-03",
    foto: "https://ui-avatars.com/api/?name=Fernanda+Goncalves&background=BA68C8&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Feminino",
    cidade: "Lucas do Rio Verde",
    estado: "MT",
    caracteristicas: "Cabelo cacheado preto, tem um cachorro de pequeno porte."
  },
  {
    id: 11,
    nome: "Daniel Barros",
    idade: 31,
    dataDesaparecimento: "2025-07-28",
    foto: "https://ui-avatars.com/api/?name=Daniel+Barros&background=00897B&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Masculino",
    cidade: "Cuiabá",
    estado: "MT",
    caracteristicas: "Alto, porte atlético, trabalha como entregador."
  },
  {
    id: 12,
    nome: "Carla Martins",
    idade: 41,
    dataDesaparecimento: "2025-06-19",
    foto: "https://ui-avatars.com/api/?name=Carla+Martins&background=FF7043&color=FFFFFF&size=400",
    status: 'LOCALIZADO',
    sexo: "Feminino",
    cidade: "Várzea Grande",
    estado: "MT",
    caracteristicas: "Manca levemente da perna esquerda, usa uma bolsa de couro marrom."
  },
  {
    id: 13,
    nome: "Roberto Nunes",
    idade: 60,
    dataDesaparecimento: "2025-08-01",
    foto: "https://ui-avatars.com/api/?name=Roberto+Nunes&background=5D4037&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Masculino",
    cidade: "Sinop",
    estado: "MT",
    caracteristicas: "Calvície aparente, costuma usar camisas sociais de manga curta."
  },
  {
    id: 14,
    nome: "Sandra Pires",
    idade: 38,
    dataDesaparecimento: "2025-09-10",
    foto: "https://ui-avatars.com/api/?name=Sandra+Pires&background=EC407A&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Feminino",
    cidade: "Rondonópolis",
    estado: "MT",
    caracteristicas: "Sotaque forte de outra região, trabalha com vendas."
  },
  {
    id: 15,
    nome: "Felipe Andrade",
    idade: 24,
    dataDesaparecimento: "2025-08-18",
    foto: "https://ui-avatars.com/api/?name=Felipe+Andrade&background=26A69A&color=FFFFFF&size=400",
    status: 'DESAPARECIDO',
    sexo: "Masculino",
    cidade: "Cuiabá",
    estado: "MT",
    caracteristicas: "Anda de skate, fones de ouvido grandes e coloridos."
  },
  {
    id: 16,
    nome: "Vanessa Ramos",
    idade: 30,
    dataDesaparecimento: "2025-03-25",
    foto: "https://ui-avatars.com/api/?name=Vanessa+Ramos&background=AB47BC&color=FFFFFF&size=400",
    status: 'LOCALIZADO',
    sexo: "Feminino",
    cidade: "Tangará da Serra",
    estado: "MT",
    caracteristicas: "Tatuagem de borboleta no pescoço."
  }
];